from enum import Enum

class Model(Enum):
    CHATGPT4OMINI = "gpt-4o-mini"
    MISTRAL = "mistral"
    LLAMA32 = "llama3.2:3b"
    QWEN25 = "qwen2.5:14b"

class Genre(Enum):
    SCIENCEFICTION = "Science Fiction"
    HIGHFANTASY = "High Fantasy"
    URBANFANTASY = "Urban Fantasy"
    GRIMDARKFANTASY = "Grimdark Fantasy"
    HISTORICALFICTION = "Historical Fiction"
    MYSTERY = "Mystery"
    DETECTIVE = "Detective"
    THRILLER = "Thriller"
    PSYCHOLOGICALTHRILLER = "Psychological Thriller"
    CYBERPUNK = "Cyberpunk"
    STEAMPUNK = "Steampunk"
    POSTAPOCALYPTIC = "Post-Apocalyptic"
    SLICEOFLIFE = "Slice of Life"
    LITERARYFICTION = "Literary Fiction"
    MAGICALREALISM = "Magical Realism"
    SLOWBURNROMANCE = "Slow Burn Romance"
    ENEMIESTOLOVERSROMANCE = "Enemies to Lovers Romance"
    COSMICHORROR = "Cosmic Horror"
    GOTHICHORROR = "Gothic Horror"
    FOLKHORROR = "Folk Horror"
    POLITICALDRAMA = "Political Drama"
    DYSTOPIANFICTION = "Dystopian Fiction"
    SATIRE = "Satire"
    DARKCOMEDY = "Dark Comedy"
    WESTERN = "Western"
    WEIRDWESTERN = "Weird Western"
    SUPERNATURAL = "Supernatural"
    OCCULT = "Occult"
    MYTHPUNK = "Mythpunk"
    ADVENTURE = "Adventure"
    EXPLORATION = "Exploration"
    ALTERNATEHISTORY = "Alternate History"


class Audience(Enum):
    CHILDREN = "Children (5-8)"
    MIDDLEGRADE = "Middle Grade (9-12)"
    YOUNGADULT = "Young Adult (13-18)"
    NEWADULT = "New Adult (18-25)"
    ADULTS = "Adults (25-45)"
    MATUREREADERS = "Mature Readers (45+)"
    GENREENTHUSIASTS = "Genre Enthusiasts"
    CASUALREADERS = "Casual Readers"
    GENERALAUDIENCE = "General Audience"
    LITERARYFICTIONREADERS = "Literary Fiction Readers"
    ENJOYEXPERIMENTALSTORYTELLING = "Enjoy experimental Storytelling"
    ENJOYNONLINEARSTORYTELLING = "Enjoy nonlinear Storytelling"
    ACADEMICS = "Academics"
    SCHOLARSOFSPECULATIVEFICTION = "Scholars of Speculative Fiction"
    RADIODRAMAFANS = "Radio Drama Fans"
    INTERACTIVEFICTIONPLAYERS = "Interactive Fiction Players"
    AUDIOBOOKLISTENERS = "Audiobook listeners"


    

class Theme(Enum):
    FORBIDDENINVENTION = "A forbidden invention that changes society"
    REDEMPTION = "Redemption through sacrifice"
    DECAYINGUTOPIA = "The decay of utopia"
    POWERCORRUPTS = "Power and its corrupting influence"
    IMMORTALITYCOSTS = "The cost of immortality"
    FRACTUREDWORLD = "Coming of age in a fractured world"
    WORLDEND = "The last day before the world ends"
    NATURERECLAIMS = "Nature reclaiming civilization"
    OUTLAWEDEMOTIONS = "A society where emotions are outlawed"
    MADNESSANDGENIUS = "The thin line between madness and genius"
    SHAPESHIFTERS = "Identity in a world of shape-shifters"
    DIVINERULE = "Rebellion against divine rule"
    FORGOTTENNAME = "The search for a forgotten name"
    DREAMWAR = "A war between dreams and reality"
    AISOUL = "Artificial intelligence gaining a soul"
    TIMETRAVEL = "Lost love through time travel"
    SENTIENTBUILDING = "A sentient building that chooses its occupants"
    ANCIENTCURSE = "An ancient curse awakened by modern greed"
    FOUNDFAMILY = "Found family in a hostile world"
    DEATHNEGOTIATION = "Death as a negotiable event"

    
    